home/urls.py
from django.urls import path
from . import views
from .views import ScheduleView, ScheduleDetail, AddMatkul, DeleteMatkul

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('about', views.about, name='about'),
    path('experience', views.experience, name='experience'),
    path('contact', views.contact, name='contact'),
    path('schedule', ScheduleView.as_view(), name='schedule'),
    path('schedule-detail/<int:pk>', ScheduleDetail.as_view(),name= 'schedule-detail'),
    path('add-matkul', AddMatkul.as_view(), name='add-matkul'),
    path('detail/<int:pk>/remove', DeleteMatkul.as_view(), name='delete'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
  path('register/', views.UserRegsiterView.as_view(), name = 'register'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

story6/urls.py
from django.urls import path
from . import views
from .views import Buku_Tamu, AddAcara, AddNama

app_name = 'story6'

urlpatterns = [
    path('bukutamu', Buku_Tamu.as_view(), name='bukutamu'),
    path('tambah-tamu', AddNama.as_view(), name='tambah-tamu'),
    path('tambah-acara', AddAcara.as_view(), name='tambah-acara')

]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.accordion, name='accordion'),
    path('data/', views.fungsi_data, name='data'),
]

home/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Matkul(models.Model):
    matkul = models.CharField(max_length=30, default='')
    dosen = models.CharField(max_length=60, default='')
    sks = models.CharField(max_length=10, default='')
    tahun = models.CharField(max_length=30, default='')
    deskripsi = models.CharField(max_length=300, default='')
    ruang = models.CharField(max_length=10, default='')
    
    def get_absolute_url(self):
        return reverse("home:schedule")

members/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models
from django.urls import reverse

class BukuTamu(models.Model):
    event = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.event
    
    def get_absolute_url(self):
        return reverse('story6:bukutamu')

class Namapeserta(models.Model):
    nama = models.CharField(max_length=30, default='')
    BukuTamu = models.ForeignKey(BukuTamu, null=True, on_delete= models.CASCADE)

    def __str__(self):
        return self.nama
    
    def get_absolute_url(self):
        return reverse('story6:bukutamu')

story7/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = [
            'matkul',
            'dosen',
            'sks',
            'tahun',
            'deskripsi',
            'ruang'
        ]
        

story6/forms.py
from django import forms
from .models import Namapeserta, BukuTamu

class AcaraForm(forms.ModelForm):
    class Meta:
        model = BukuTamu
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "What do you want to do ?"}),
        }
class NamaForm(forms.ModelForm):
    class Meta:
        model = Namapeserta
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "What is your name?"}),
        }

home/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .forms import MatkulForm
from .models import Matkul
from django.urls import reverse_lazy

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about.html')

def experience(request):
    return render(request, 'home/experience.html')

def contact(request):
    return render(request, 'home/contact.html')

class ScheduleView(ListView):
    model = Matkul
    template_name = 'home/schedule.html'
class ScheduleDetail(DetailView):
    model = Matkul
    template_name = 'home/scheduledetails.html'
class AddMatkul(CreateView):
    model = Matkul
    template_name = 'home/addschedule.html'
    fields = '__all__'
class DeleteMatkul(DeleteView):
    model = Matkul
    template_name = 'home/deletematkul.html'
    success_url = reverse_lazy('home:schedule')

members/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class UserRegsiterView(generic.CreateView):
  form_class = UserCreationForm
  template_name = 'registration/register.html'
  success_url = reverse_lazy('login')

story6/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import BukuTamu, Namapeserta

class Buku_Tamu(ListView):
  context_object_name = 'list'
  template_name = 'bukutamu.html'
  queryset = BukuTamu.objects.all()

  def get_context_data(self, **kwargs):
    context = super(Buku_Tamu, self).get_context_data(**kwargs)
    context['nama_peserta'] = Namapeserta.objects.all()
    return context

class AddNama(CreateView):
    model = Namapeserta
    template_name = 'tambahtamu.html'
    fields = '__all__'

class AddAcara(CreateView):
    model = BukuTamu
    template_name = 'tambahacara.html'
    fields = '__all__'

story7/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def accordion(request):
    return render(request, 'accordion.html')

def fungsi_data(request):
    arg = request.GET['search']
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    r = requests.get(url_tujuan)
    data = json.loads(r.content)
    return JsonResponse(data, safe=False)

home/templates/home/about.html
{% extends 'base.html'%}
{% block content %}
<div class="grid-main-container">
  <div class="picture-container">
    <img src="../static/home/image/home/foto-red.png" alt="red-pic">
    <img src="../static/home/image/home/foto-cyan.png" alt="cyan-pic">
    <img src="../static/home/image/home/foto-yellow.png" alt="yellow-pic">
    <img src="../static/home/image/home/foto.jpg" alt="display-pic">
  </div>
  <div class="flex-column-container">
    <h2>Maheswara Ananta Argono</h2>
    <h2>Computer Science 2019</h2>
    <h2>University Of Indonesia</h2>
    <h2>NPM : 1906398471</h2>
  </div>
  <div class="layerbox">
    <div class="description-box">
      <div class="interest-title">
        <h3 data-title="DESCRIPTION">DESCRIPTION</h3>
      </div>
      <p>Hi my name is Anan! In the making of this website, I am currently 19 years old. I am very passionate about programming, that is why i went to study computer science as my major subject in university. My source of motivation towards programming drives me to do my best and be more eager in improving my computer science skill.</p>
  </div>
  </div>
  <div class="astronaut">
    <img src="../static/home/image/home/RealAstro.png" alt="astronaut">
  </div>
  <div class="futuristic">
    <h1 class="Fut"data-title="Future Programmer">Future Programmer</h1>
  </div>
  <div class="interest">
    <div class="interest-box">
      <div class="interest-title">
        <h3 data-title="INTEREST">INTEREST</h3>
      </div>
      <h4>
        WEB DEVELOPMENT<br>
        GAME DEVELOPMENT<br>
        CYCLING
      </h4>
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/addschedule.html
{% extends 'base.html'%}
{% block content %}
<div class="flex-container schedule-details align-items-center justify-content-center">
  <div class="add-form">
    <h2>Addding New Subject...</h2>
    <form method = "POST" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    </form>
  </div>
</div>
{% endblock %}

home/templates/home/contact.html
{% extends 'base.html'%}
{% block content %}
<div class="contact-flex">
  <div class="flex-column-container" id="contact">
    <div class="contact-icon">
      <i class="fab fa-instagram-square"></i></i><h2>@anantus</h2><br>
    </div>
    <div class="contact-icon">
      <i class="fas fa-envelope-square"></i><h2>maheswaraananta@gmail.com</h2><br>
    </div>
    <div class="contact-icon">
      <i class="fab fa-linkedin"></i><h2>maheswara ananta</h2><br>
    </div>
    <div class="contact-icon">
      <i class="fas fa-address-book"></i><h2>+62 813 1792 7436</h2><br>
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/deletematkul.html
{% extends 'base.html'%}
{% block content %}
<div class="contact-flex schedule-details">
  <div class="flex-column-container delete-box" id="contact">
    <h2>Delete Mata Kuliah</h2>
    <form method = "POST" >
      {% csrf_token %}
      <!-- <button type="button" name="submit" class="btn btn-warning">ADD</button> -->
      <p class="confirmDeletion">
          Are you sure you want to delete {{matkul.matkul}} from this list?
      </p>
      <input type="submit" value="Delete" />
      </form>
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/experience.html
{% extends 'base.html'%}
{% block content %}
<div class="grid-main-container" id="grid-experience">
  <div class="education">
    <img src="../static/home/image/home/Education.png" alt="education">
  </div>
  
  <div class="layerbox" id="skill">
    <div class="description-box" >
      <div class="interest-title">
        <h3 data-title="SKILLS">SKILLS</h3>
      </div>
      <i class="fab fa-java"></i>
      <i class="fab fa-html5"></i>
      <i class="fab fa-css3-alt"></i><br>
      <i class="fab fa-python"></i>
      <i class="fab fa-adobe"></i>
    </div>
  </div>
  <div class="cd">
    <img src="../static/home/image/home/cd.gif" alt="" class="cd-player">
  </div>
  <div class="organization-pic">
    <img src="../static/home/image/home/litbang.jpg" alt="foto litbang">
  </div>
  <div class="history">
    <div class="organization-title">
      <h3 data-title="ORGANIZATION">ORGANIZATION</h3>
    </div>
  </div>
  <div class="organization">
    <h2 class="org-mobile">ORGANIZATION</h2>
    <h2>BEM UI: Research and<br>Development</h2>
    <h2>Mentor of Python<br>programming basics</h2>
    <h2>High School Computer<br>Science Club</h2>
  </div>
</div>
{% endblock %}

home/templates/home/form.html
{% extends 'base.html'%}
{% block title%} Matkul - Maheswara Ananta {% endblock %}
{% block content %}
<div class="navblock"></div>
<div class="contact-flex">
  <div class="flex-column-container" id="contact">
    <div class="titleMatkul align-items-center">
      <h2>Mata Kuliah</h2><a href="{%url 'home:add-matkul' %}"><h2 class="add-icon"> ADD </h2></a><br>
    </div>
    {% for matkul in object_list %}
      <h2 class="scheduleList"><a href="{% url 'home:schedule-detail' matkul.pk %}">{{matkul.matkul}} - {{matkul.dosen}}</h2></a> 
      <a href="{%url 'home:delete' matkul.pk %}" class="deletematkul"><h3 class="delete-icon">X</h3></a><br>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html'%}
{% block content %}
<div class="flex-container">
  <div id="middle-bg">
    <h1 class="greeting" data-title="Hi, my name is Anan!" href="#About">Hi, my name is Anan!</h1>
  </div>
</div>
{% endblock %}

home/templates/home/schedule.html
{% extends 'base.html'%}
{% block title%} Matkul - Maheswara Ananta {% endblock %}
{% block content %}
<div class="navblock"></div>
<div class="contact-flex">
  <div class="flex-column-container" id="contact">
    <div class="titleMatkul align-items-center">
      <h2>Mata Kuliah</h2><a href="{%url 'home:add-matkul' %}"><h2 class="add-icon"> ADD </h2></a><br>
    </div>
    {% for matkul in object_list %}
      <h2 class="scheduleList"><a href="{% url 'home:schedule-detail' matkul.pk %}">{{matkul.matkul}} - {{matkul.dosen}}</h2></a> 
      <a href="{%url 'home:delete' matkul.pk %}" class="deletematkul"><h3 class="delete-icon">X</h3></a><br>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/scheduledetails.html
{% extends 'base.html'%}
{% block content %}
<div class="contact-flex schedule-details">
  <div class="flex-column-container" id="contact">
    <h2>Mata Kuliah : {{matkul.matkul}}</h2><br>
    <h2>Dosen : {{matkul.dosen}}</h2><br>
    <h2>SKS : {{matkul.sks}}</h2><br>
    <h2>Tahun : {{matkul.tahun}}</h2><br>
    <h2>Deskripsi : {{matkul.deskripsi}}</h2><br>
    <h2>Ruang : {{matkul.ruang}}</h2><br>
    <h2 class="back"><a href="{%url 'home:schedule'%}">Back</a></h2>
    </div>
  </div>
</div>
{% endblock %}
Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis blanditiis, odio doloremque, libero labore ex a harum est id explicabo unde! Praesentium eius vero odit sapiente! Delectus laudantium nisi libero?

home/templates/home/story1.html
{% extends 'base.html'%}
{% block content %}
    <div class="flexbox-container-s1">
        <div class="flexbox-item item-1-s1"><img src="../static/home/image/home/foto.jpg" alt = "foto Anan"></div>
        <div class="flexbox-item-s1 item-2-s1">
            <h2 class="s">Hi</h2> 
            <h2 class="s">I'm</h2> 
            <h2 class="s">Anan</h2>  
            <h2 class="s">!</h2>  
            <p class="s">
                Maheswara Ananta Argono | 1906398471 <br>
                Fasilkom UI 2019, Future Programmer
            </p>  
        </div>
    </div>
    <div class="grid-container-s1">
        <div class=" grid-item-s1 grid-1-s1">
            <h3 class="s">DESCRIPTION</h3>
            <p class="s">
                I am very passionate about programming, that is why i went to study computer science as my major subject in university. My source of motivation towards programming drives me to do my best and be more eager in improving my computer science skill.
            </p>
        </div>
        <div class=" grid-item-s1 grid-2-s1">
            <h3 class="s">HOBBIES</h3>
            <p class="s">
                <ul class="s">
                    <li class="s">Gaming</li>
                    <li class="s">Watch Movies</li>
                    <li class="s">Cycling</li>
                    <li class="s">Coding</li>
                </ul>
            </p>
        </div>
        <div class="grid-item-s1 grid-3-s1">
            <h3 class="s">PREVIOUS EDUCATION</h3>
            <p id="school-s1">
                SD Mentari Intercultural School Bintaro (2007-2013) <br>
                SMP Highfield  (2013 - 2016) <br>
                SMAK 7 BPK PENABUR (2016 - 2019)
            </p>
        </div>
    </div>
{% endblock %}

story6/templates/bukutamu.html
{% extends 'base.html'%}
{% block content %}
<div class="navblock"></div>
<h2>Buku Tamu</h2><br> 
<div class="d-flex flex-wrap">
  {% for acara in list %}
  <div class="p-2 bd-highlight bg-white">
    <h4 class="nama-acara">{{ acara }}</h4>
    {% for na in nama_peserta %}
      {% if na.BukuTamu == acara%}
      <p class="nama-peserta">{{ na }}</p>
      {% endif %}
    {% endfor %}
    <a href="/story6/tambah-tamu">Daftar Tamu</a>
  </div>
  {% endfor %}
  <div>
    <a href="/story6/tambah-acara">
      <h2>
        Tambah<br>
        Acara
      </h2>
    </a>
  </div>
</div>
{% endblock %}

story6/templates/tambahacara.html
{% extends 'base.html'%}
{% block title%} Tambah Acara {% endblock %}
{% block content %}
<div class="flex-container schedule-details align-items-center justify-content-center">
  <div class="add-form">
    <h2>Tambahkan Acara</h2>
    <form method = "POST" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    </form>
  </div>
</div>
{% endblock %}

story6/templates/tambahtamu.html
{% extends 'base.html'%}
{% block title%} Daftar acara - Maheswara Ananta {% endblock %}
{% block content %}
<div class="flex-container schedule-details align-items-center justify-content-center">
  <div class="add-form">
    <h2>Daftarkan Acara</h2>
    <form method = "POST" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    </form>
  </div>
</div>
{% endblock %}

story7/templates/accordion.html
{% extends 'base.html'%}
{% load static %}
{% block css%}
<link rel="stylesheet" href="{% static 'anotherstyle.css' %}" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}
{% block content %}
<div class="navblock"></div>
<h1>Accordion</h1>
  <div class="accordion container">
    <div class="OrderingField row">
      <div class="col-auto d-flex flex-column justify-content-center align-items-stretch">
        <button value='up' class="btn btn-success">Up</button>
			  <button value='down' class="btn btn-warning">Down</button>
      </div>
      <div class="col">
        <div class="accordion-header">Search Items</div>
        <div class="accordion-content">
          <div class="input-group input-group-sm mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text bg-danger text-white" id="inputGroup-sizing-sm">Search Books</span>
            </div>
            <input type="text" class="form-control" id="keyword" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
          </div>
          <ol id="hasil">
          </ol>
        </div>
      </div>
    </div>
    <div class="OrderingField row">
      <div class="col-auto d-flex flex-column justify-content-center align-items-stretch">
        <button value='up' class="btn btn-success">Up</button>
			  <button value='down' class="btn btn-warning">Down</button>
      </div>
      <div class="col">
        <div class="accordion-header">Organisasi/Panitia</div>
        <div class="accordion-content">Saat ini saya hanya mengikuti Organisasi Biro penelitian dan pengembangan bem ui 2020, namun sebelumnya saya pernah mengikuti OSIS SMP dan Sains Club Jenjang Informatika</div>
      </div>
    </div>
    <div class="OrderingField row">
      <div class="col-auto d-flex flex-column justify-content-center align-items-stretch">
        <button value='up' class="btn btn-success">Up</button>
			  <button value='down' class="btn btn-warning">Down</button>
      </div>
      <div class="col">
        <div class="accordion-header">Prestasi</div>
        <div class="accordion-content">Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon! Coming Soon!</div>
      </div>
    </div>
    <div class="OrderingField row">
      <div class="col-auto d-flex flex-column justify-content-center align-items-stretch">
        <button value='up' class="btn btn-success">Up</button>
			  <button value='down' class="btn btn-warning">Down</button>
      </div>
      <div class="col">
        <div class="accordion-header">Goals</div>
        <div class="accordion-content">Lulus di waktu yang tepat, dapet banyak ilmu dan bisa mengimplementasikan ilmunya untuk sesuatu yang benar.</div>
      </div>
    </div>
    
</div>
{% endblock %}
{% block script%}
<script>
  $(".accordion").on("click", ".accordion-header", function() {
  $(this).toggleClass("active").next().slideToggle();
});
function moveUp(item) {
    var prev = item.prev();
    if (prev.length == 0)
        return;
    prev.css('z-index', 999).css('position','relative').animate({ top: item.height() }, 250);
    item.css('z-index', 1000).css('position', 'relative').animate({ top: '-' + prev.height() }, 300, function () {
        prev.css('z-index', '').css('top', '').css('position', '');
        item.css('z-index', '').css('top', '').css('position', '');
        item.insertBefore(prev);
    });
}
function moveDown(item) {
    var next = item.next();
    if (next.length == 0)
        return;
    next.css('z-index', 999).css('position', 'relative').animate({ top: '-' + item.height() }, 250);
    item.css('z-index', 1000).css('position', 'relative').animate({ top: next.height() }, 300, function () {
        next.css('z-index', '').css('top', '').css('position', '');
        item.css('z-index', '').css('top', '').css('position', '');
        item.insertAfter(next);
    });
}

$(".FieldContainer").sortable({ items: ".OrderingField", distance: 10 });
$('button').click(function() { 
    var btn = $(this);
    var val = btn.val();
    if (val == 'up')
        moveUp(btn.parents('.OrderingField'));
    else
        moveDown(btn.parents('.OrderingField'));
});


$('.FieldContainer a.add').click(function(){

    $('.FieldContainer').append(

    '<div class="OrderingField">'+
    '<div class="LeftFloat">'+
    'Item'+
    '</div>'+
    '<div class="RightFloat Commands">'+
    '<button value="up" >Up</button>'+
    '<button value="down" >Down</button>'+
    '</div>'+
    '</div>');

    $(".FieldContainer").sortable("destroy");

$(".FieldContainer").sortable({ items: ".OrderingField", distance: 10 });
$('button').click(function() { 
    var btn = $(this);
    var val = btn.val();
    if (val == 'up')
        moveUp(btn.parents('.OrderingField'));
    else
        moveDown(btn.parents('.OrderingField'));
});
});

$("#keyword").keyup( function(){
    var isi_keyword = $("#keyword").val();
    console.log(isi_keyword);
    var url_utk_dipanggil = '/story7/data?search=' + isi_keyword;
    console.log(url_utk_dipanggil);
    $.ajax({
      url: url_utk_dipanggil,
      success: function(hasil) {
        console.log(hasil.items);
        var obj_hasil = $("#hasil");
        obj_hasil.empty();

        for(i = 0; i < hasil.items.length; i++){
          var tmp_title = hasil.items[i].volumeInfo.title;
          var tmp_thumbnails = hasil.items[i].volumeInfo.imageLinks.smallThumbnail;
          var tmp_publisher = hasil.items[i].volumeInfo.publisher
          var tmp_link = hasil.items[i].volumeInfo.canonicalVolumeLink;

          console.log(tmp_title);
          obj_hasil.append('<li> Title : <br>   ' + tmp_title + '<br> Publisher  :<br>    '+ tmp_publisher +'<br> <img src=' + tmp_thumbnails + '> </li>')
        }
      }
    })
})
</script>
{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
   <!-- <link rel="stylesheet" href="{% static 'home/style.css' %}" type="text/css"> -->
   {% block css%}
   {% endblock %}
   <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Secular%20One">
   <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Red%20Rose">
   <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Roboto">
   <script src="https://kit.fontawesome.com/4c0a41235a.js" crossorigin="anonymous"></script>
  <title>Maheswara Webpage</title>
</head>
<body>
<!-- ---------------NavBar------------------ -->
  <header>
    <div class="container">
      <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
          <img src="../static/home/image/home/playpause.png" height="25"class="d-inline-block align-top" alt="" loading="lazy">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:experience' %}">Experience</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story7:accordion' %}">Accordion</a>
            </li>
            {%if user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:schedule' %}">Schedule</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story6:bukutamu' %}">Activity</a>
            </li>
            {%endif%}
          </ul>
        </div>
        <form class="form-inline">
          {%if user.is_authenticated%}
            <a class="text-white">Welcome {{user.username}}!</a>
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {%else%}
            <a class="nav-link" href="{% url 'members:register' %}">Register</a>
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          {%endif%}
        </form>
      </nav>
    </div>
  </header>
  {% block content %}
  {% endblock %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  {% block script %}
  {% endblock %}
</body>
</html>